/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { TaskboardRemoteMutationRequest, TaskboardRemoteMutationResult } from '@shengsheng/dsh-taskboard/domain'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$7461736b626f617264 {
    mutate: (request: TaskboardRemoteMutationRequest) => Promise<RemoteResult<TaskboardRemoteMutationResult>>
    snapshot: (projectId?: string) => Promise<RemoteResult<string>>
    taskDetail: (taskId: string) => Promise<RemoteResult<string>>
  }
  interface TypertRemoteMap {
    'taskboard/mutate': (request: TaskboardRemoteMutationRequest) => Promise<RemoteResult<TaskboardRemoteMutationResult>>
    'taskboard/snapshot': (projectId?: string) => Promise<RemoteResult<string>>
    'taskboard/taskDetail': (taskId: string) => Promise<RemoteResult<string>>
  }
  interface TypertRemoteNamespaceMap {
    'taskboard': TypertRemoteNamespace$7461736b626f617264
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
